# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Clinton Fernandes
email: clintoncleetus17@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cloud-native backend engineer sharing real-world Java, React, and AWS
  projects. Dive into serverless architectures, distributed systems, and
  production-ready code walkthroughs. Learn how to build scalable,
  cost-efficient apps on the modern web.
twitter_username: MinimalDebugger
github_username: clinton1719
minimal_mistakes_skin: contrast
search: true

url: "https://clinton1719.github.io"
baseurl: "/clinton-blogs"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Clinton Fernandes"
  avatar : "/assets/images/profile_picture.jpg"
  bio    : "Cloud-native backend engineer sharing real-world Java, React, and AWS
  projects. Dive into serverless architectures, distributed systems, and
  production-ready code walkthroughs. Learn how to build scalable,
  cost-efficient apps on the modern web."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/MinimalDebugger"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clinton1719"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/clinton-fernandes-45932915a/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/MinimalDebugger"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clinton1719"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/clinton-fernandes-45932915a/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
